version: '3'
services:
  pgdb:
    container_name: db-node
    image: postgres:14
    restart: 'no'
    ports: 
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - ./pgdata:/var/lib/postgresql/data/pgdata

